### ISSUE TITLE
Supertoken the system coin

### ISSUE THREAD

**Issue by cupOJoseph** [open-dollar/od-contracts#101]
add superfluid library to system coin

https://github.com/superfluid-finance/custom-supertokens/blob/main/contracts/PureSuperToken.sol

**Comment by pi0neerpat** [comment]
### Primary Resources

- FOTToken example https://github.com/superfluid-finance/custom-supertokens/blob/FOTToken/contracts/experimental/FOTToken.sol
- "recipe" of how to taken any token contract and turn it into a PureSuperToken: https://github.com/superfluid-finance/custom-supertokens/blob/FOTToken/contracts/experimental/FOTToken.sol This contract inherits from SuperTokenStorage (will be replaced with SuperTokenBase: https://github.com/superfluid-finance/custom-supertokens/blob/FOTToken/contracts/base/SuperTokenBase.sol) which inherits both SuperTokenStorage and UUPSProxy

> SuperTokenStorage: storage padding 32 reserved slots for SuperToken logic contract.
UUPSProxy: making this contract a proxy which will point at the canonical SuperTokenLogic (in the initializeCustomerSuperToken function called in the constructor)


### Other resources:

- Changes to allow for the "devolution" of supertokens: https://github.com/superfluid-finance/protocol-monorepo/issues/1685

**Comment by pi0neerpat** [comment]
Delayed until after testnet

**Comment by daopunk** [comment]
Superfluid team has not replied about when they will transition away from multisig, so there is still unknown risk associated with this integration.

Recommended next step:
We cut this from V1, and potentially do integration in a future version.

**Comment by pi0neerpat** [comment]
Closing for now. Will circle back if things change
