### ISSUE TITLE
combine transferExtraSurplus and auctionSurplus functions to be more streamlined

### ISSUE THREAD

**Issue by cupOJoseph** [open-dollar/od-contracts#122]
https://github.com/hai-on-op/core/pull/10
fulfill all of the suggestions here

- rename system param to `surplusTransferPercentage `
- combine transferExtraSurplus and auctionSurplus functions
- use WAD % units
- add parameter validation

**Comment by pi0neerpat** [comment]
Feedback: May be an alternative option:
- Use the split earlier in the tax collector, rather than sending and splitting in the surplus
