### ISSUE TITLE
determine who is msg.sender in safeHandler constructor call

### ISSUE THREAD

**Issue by cupOJoseph** [open-dollar/od-contracts#13]
is this SAFEManager or end user? how is this address used and should it be set the the NFT contract address?

ISAFEEngine(_safeEngine).approveSAFEModification( msg.sender);

**Comment by daopunk** [comment]
the `msg.sender` here refers to the safeManager

the creation of the safeHandler serves as an identification of a Safe

the `approveSAFEModification` function in the SAFEEngine sets a mapping to `safeRights[safeHandler][safeManager]` where the safeManager can modify the Safe
