### ISSUE TITLE
Add properties to NFT

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#134]
Currently, the NFT URIs are formatted like:

```
{
  "name": "Open Dollar Vault",
  "description": "vaultId: 1 collateral: 1000000000000000000000-FTRG debt: 1000000000000000000000-OD ratio: 79 stabilityFee: 1000000011119260000000000000 risk: LIQUIDATION",
  "image": "data:image/svg+xml;base64,PHN2ZyB3aW..."
}
```

However, the URI should use properties/values, so that attributes are visible on NFT indexing sites

![image](https://github.com/open-dollar/od-contracts/assets/35622595/e9e13bb0-b7eb-4475-9ae7-707514393ab3)

All properties visible on the NFT should be included. Here is an example list with property names and values:

- ID: "123"
- Debt: "123,123.00"
- Collateral amount: "234.00"
- Collateral Type: "wBTC"
- Stability Fee: "1.3%"
- Risk: "Low Risk"
- Collateral Ratio: "180%"
- Last Update Time: "Jan 5, 2023 20:45 UTC"

**Comment by daopunk** [comment]
<img width="478" alt="Screenshot 2023-09-26 at 3 03 54 PM" src="https://github.com/open-dollar/od-contracts/assets/50965054/8b73d2a5-374a-40b3-b314-48103efa1bb2">

**Comment by daopunk** [comment]
<img width="552" alt="Screenshot 2023-09-26 at 3 05 56 PM" src="https://github.com/open-dollar/od-contracts/assets/50965054/6cf9eb2d-bd2b-42a1-b43f-b2dc7bfaf87d">
