### ISSUE TITLE
Fix Linter

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#156]
- [ ] e2e tests github action should pass
- [ ] Linting github action should pass

**Comment by daopunk** [comment]
current linter issue
- linter triggered by incorrect spacing on deployments

**Comment by pi0neerpat** [comment]
Pretty sure this is why I had the script formatted the previous way:

https://github.com/open-dollar/od-contracts/commit/c2f6c4d79f5101714a6612a2855c0da76ebf00e3#diff-ce1a0422d42bfc315a0d0d0664adb9e4f2b0ab34456fa580cbece7219be37044
