### ISSUE TITLE
send SF to primary before secondary receivers in tax collector

### ISSUE THREAD

**Issue by cupOJoseph** [open-dollar/od-contracts#167]
shouldnt secondary receivers go after the primary receiver? maybe?

https://github.com/open-dollar/od-contracts/blob/6e12defbebf3a0a3e6219d7157bda12a52c1af54/src/contracts/TaxCollector.sol#L256-L257

**Comment by pi0neerpat** [comment]
Thanks to #122, we wont be adding any additional `extraSurplusReceiver`. 

May be a bug from hai

**Comment by cupOJoseph** [comment]
The order doesnt matter since every receiver gets the same `_debtAmount `. But actually I think the debt amount could be incorrect here and should be _debtAmount/number of receivers 
I contacted HAI and followed up with wei3 in DMs


tax flow diagram
https://www.figma.com/file/zj1c6EBUYDVIRhldDM3oOu/fees-distribution?type=whiteboard&node-id=0%3A1&t=X6z81cyBF0yPGxNB-1
