### ISSUE TITLE
NFV QA 10-12

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#186]
![image](https://github.com/open-dollar/od-contracts/assets/35622595/97df8a0e-d758-4460-baa7-557102e4547c)

- [x] Attributes collateral and debt should be parsed to the correct decimal amount. Commas are not necessary.

![image](https://github.com/open-dollar/od-contracts/assets/35622595/01b4ea46-3a84-4409-8ea0-2194db294196)

- [x] Item title should be

> OD NFV #1

![image](https://github.com/open-dollar/od-contracts/assets/35622595/f3875292-e6b6-43bc-bbdb-baaa3bf3b84d)

- [x] Item description should be

> Non-Fungible Vault #1
> 
> Caution! Trading this NFV gives the recipient full ownership of your Vault, including all collateral & debt obligations. This act is irreversible.

- [x] Collection description should be:

> Open Dollar is a DeFi lending protocol that enables borrowing against liquid staking tokens while earning staking rewards and enabling liquidity via Non-Fungible Vaults (NFVs).

**Comment by daopunk** [comment]
For item 1
"Attributes collateral and debt should be parsed to the correct decimal amount. Commas are not necessary."

Do you mean to parse the number to 18 decimal (or appropriate decimal)?

**Comment by daopunk** [comment]
![Image](https://github.com/open-dollar/od-contracts/assets/50965054/2191d94d-da6f-4068-bf52-65e020c65a7e)
