### ISSUE TITLE
Governance Operations: Collateral Add

### ISSUE THREAD

**Issue by daopunk** [open-dollar/od-contracts#225]
Depends on #241 
- List likely governance operations as Primary Governance Operations
- Create scripts for all PGOs
- Demonstrate success of scripts on live testnet

**Comment by pi0neerpat** [comment]
Required for updated SVG renderer

**Comment by daopunk** [comment]
3 opereations
- collateral
- nft image update
- PID controller

**Comment by daopunk** [comment]
example for collateral add w/ DAO:
https://github.com/open-dollar/od-contracts/blob/dev/test/testlocal/nft/anvil/governor/AddCollateral.t.sol
https://github.com/open-dollar/od-contracts/blob/dev/test/testlocal/nft/goerli/governor/AddCollateral.t.sol

**Comment by 0xdavinchee** [comment]
output is a script file and tests for each that allows governance to create a proposal.
