### ISSUE TITLE
deploy NFT contract and OD token contract to effecient address starting with 0D

### ISSUE THREAD

**Issue by cupOJoseph** [open-dollar/od-contracts#25]
use create2 to deploy prod nft contract and OD token contract and ODG gov token contract if possible to addresses that start with `0x0D000` and have as many 0s as possible

**Comment by daopunk** [comment]
precompute in solidity
```
  function _precomputeAddress(bytes memory _bytecode, uint256 _salt) internal returns (address) {
    return address(bytes20(keccak256(abi.encodePacked(bytes1(0xff), address(this), _salt, keccak256(_bytecode)))));
  }
```

need to mimic this method in another language off-chain to create vanity address, where address(this) is the create2 factory that will deploy the vanity contract

**Comment by daopunk** [comment]
Forge has a script for this:
https://book.getfoundry.sh/reference/cast/cast-create2
