### ISSUE TITLE
Frontrunning Token Transfer

### ISSUE THREAD

**Issue by daopunk** [open-dollar/od-contracts#277]
Currently, a NFV transfer TX can be frontrun, where collateral is drained or debt is maxed before transfer, resulting in the loss of value for the buyer.

There are 2 solutions:
1. Use TX nonce or hash of token state with a condition on token transfer to prevent transfer if state change has occurred.
2. Put delay on token transfer, where transfers can only happen after `n` time, so that any change in the amount of debt and/or collateral associated with the token triggers a time delay preventing a token transfer until time is expired.

Solution 1 is preferred, but is incompatible with existing NFT markets. Solution 2 is compatible with existing NFT markets, however it is inconvenient due to `n` time delay.

Expected outcome:
Create a hybrid solution where token defaults to solution 2 for generic NFT markets, however can opt for solution 1 is the NFT market address is registered with Vault721 - meaning it implements a state check using the nonce or state hash of the NFV.

**Comment by St4rgarden** [comment]
@daopunk @pi0neerpat  Let's discuss:

I think this should be two different issues certainly.  The second proposed implementation should be fairly easy.

I will take a deeper look today but at a glance here's my approach:

- Vault721 will need a configurable `executionDelay` state variable
- The individual proxies must store and update a timestamp each time that `execute` is called; `lastExecution`
- Each time the `_afterTokenTransfer` hook is invoked; we must check the current time, last execution and the execution delay.

This will require the following changes:

Vault721.sol:

```
uint256 internal executionDelay;
uint256 internal minDelay;

function setExecutionDelay(uint256 delay) public onlyGovernance {
  require (executionDelay > minDelay, "Short Delay");
  executionDelay = delay;
  
  /**
   * @dev _transfer calls `transferSAFEOwnership` on SafeManager
   * enforces that ODProxy exists for transfer or it deploys a new ODProxy for receiver of vault/nft
   */
  function _afterTokenTransfer(address from, address to, uint256 firstTokenId, uint256 batchSize) internal override {
    require(to != address(0), 'V721: no burn');
    if (from != address(0)) {
      address payable proxy;

      if (_isNotProxy(to)) {
        proxy = _build(to);
      } else {
        proxy = payable(_userRegistry[to]);
      }
      
      uint256 lastExecution = IProxy(to).getLastExecution();
      if (lastExecution > block.timestamp + executionDelay) {
        revert FrontRunBlock();
      }
      IODSafeManager(safeManager).transferSAFEOwnership(firstTokenId, address(proxy));
    }
  }
```

ODProxy.sol:

```

uint256 private lastExecution;

function getLastExecution() returns(uint256 lastExecution) {}

function execute(address _target, bytes memory _data) external payable onlyOwner returns (bytes memory _response) {
    if (_target == address(0)) revert TargetAddressRequired();
    lastExecution == block.timestamp;

    bool _succeeded;
    (_succeeded, _response) = _target.delegatecall(_data);

    if (!_succeeded) {
      revert TargetCallFailed(_response);
    }
  }
```
 
 Kind of just spitballing here there may be some additional considerations.
 
 Please let me know if this feels like a decent solution; and then we can discuss hybridizing this to provide flexibility for approved marketplaces.

**Comment by daopunk** [comment]
As it is the weekend, I won't do an in-depth review of this until Monday. I will come back with more details then, but rough idea of what I'm thinking is using existing view functions in the NFTRenderer to get collateral and debt data, hash that together as a state identifier, save that state hash in a mapping on Vault721 where the tokenId points the lastStateHash.

Similarly, a mapping can map the tokenId to the lastTx in the case of the time locked default solution. 

Instead of having 2 mappings, perhaps we have 1 mapping to a struct with these 2 variables in them. I will think more on this and give a more detailed answer on Monday.

**Comment by St4rgarden** [comment]
> As it is the weekend, I won't do an in-depth review of this until Monday. I will come back with more details then, but rough idea of what I'm thinking is using existing view functions in the NFTRenderer to get collateral and debt data, hash that together as a state identifier, save that state hash in a mapping on Vault721 where the tokenId points the lastStateHash.
> 
> Similarly, a mapping can map the tokenId to the lastTx in the case of the time locked default solution.
> 
> Instead of having 2 mappings, perhaps we have 1 mapping to a struct with these 2 variables in them. I will think more on this and give a more detailed answer on Monday.

@cupOJoseph @pi0neerpat @daopunk 

The problem I am having trying to conceptualize a solution for this is:

At the lowest level calls directly to the SafeEngine can impact the debt and collateral in a SAFE.  So there's almost no way I can see without modifying the SafeEngine itself to enforce that there have not been any changes.  Not sure if any of the higher level abstractions will actually work like changing the ODSafeManager or Vault721 etc.  It's unfortunately a very opinionated problem built on an extremely un-opinionated protocol.

The reason I chose to attempt implementing a solution from the ODProxy was that the Proxy is a requirement of system IE you can't create an NSV without the proxy.

An escrow contract really might be the solution:  

## Seaport Escrow Contract:

Using the order struct from Seaport:

```
struct Order {
  struct OrderParameters parameters;
  bytes signature;
}
```

```
struct OrderParameters {
  address offerer;
  address zone;
  struct OfferItem[] offer;
  struct ConsiderationItem[] consideration;
  enum OrderType orderType;
  uint256 startTime;
  uint256 endTime;
  bytes32 zoneHash;
  uint256 salt;
  bytes32 conduitKey;
  uint256 totalOriginalConsiderationItems;
}
```

- User approves escrow via ERC721
- User calls `deposit(tokenId, order)`
- Contract takes the token from user and records the ownership information, a SAFE state hash and the order hash; possibly calling `validate(order)` via Seaport OR alternatively implementing `isValidSignature` EIP1271
- During order fulfillment Seaport first checks if an order is already validated; then if it's not validated - checks if the token holder is a contract and calls `isValidSignature` on the token owner
- The part which is unknown to me currently is if calling `validate` on Seaport is automatically detected by Opensea and added to their front-end
- We may actually have to implement Opensea API in order to push the item up to the marketplace's Front End.

[You can see more about the Seaport fulfillment policy flow here](https://www.figma.com/file/QAl3vlXr0B6BG4nIDskD5q/Seaport-Contract-Policy-flow?type=whiteboard&node-id=0-1&t=fmeLrvmoXAIncXol-0)

**Comment by daopunk** [comment]
Assigning this to @0xdavinchee since you have 2 other issues that depend on this solution (#217 & #382), as well as NFT Marketplace research that will also depend on this solution.

Task: implement hybrid solution to accommodate traditional and new NFT marketplaces (see 1st comment)

Considerations:
For time-delay solution to be used in traditional NFT Marketplaces:
- ensure that NFVs cannot have collateral or debt changed directly in SafeEngine (thus making delay irrelevant if NFV is not aware of changes)

For hash state solution to be used in future (our) NFT Marketplaces:
- use view getter functions in NFTRenderer to get collateral and debt token amounts, and hash those values together
- make state hashes accessible to future NFT Marketplace

**Comment by daopunk** [comment]
Considerations:

**Vault721**
primary contract to add frontrunning protection logic
should contain any data structures needed to keep track of state-hash and time-delay vars

**SafeEngine**
audit for vulnerabilities in the context of NFV frontrunning
what functions can be called direct from Proxy => SafeEngine (via basicActions)
can these direct calls modify debt and collateral without Vault721 being notified? (this is a concern for the time-delay, not for the state-hash solution)

**SafeManager**
should call to reset time-delay var in Vault721 during transactions that modify debt and collateral

**NFTRender**
has view getter functions that lookup collateral and debt amounts
get collateral and debt amounts, and hash together for state var

Summary:

Time-delay solution poses more risks than the state-hash solution, as it requires that SafeManger notifies Vault721 of relevant transactions in order to reset the time-delay var. It also poses a risk around direct calls to the SafeEngine, so this needs to be audited and resolved.

State-hash solution is simpler and more secure. It only requires getting debt and collateral amounts to create a state-hash, which only requires Vault721 and NFTRenderer contracts.

**Comment by daopunk** [comment]
State-hash should be calculated during the tokenTransfer, and compared to the last state-hash, which is required to be at least 1 block older than the current block.

**Comment by daopunk** [comment]
State-hash should be calculated during the tokenTransfer, and compared to the last state-hash, which is required to be at least 1 block older than the current block.

**Comment by daopunk** [comment]
For the NFT Market that we build in the future:

The NftMarket contract that is whitelisted to Vault721, will check NFV lastHash against the frontend application, which will have the lastHash saved from the JSON it grabbed when updating the token image with the tokenURI function. So, when someone buys and NFV, the lastHash on the website is compared to the lasHash in Vault721, and then the transfer begins, and finally in the afterTransfer hook the block-level currentHash is compared to the lastHash. If any comparison fails, it all reverts.

**Comment by St4rgarden** [comment]
Guys I don't think we want to have to create an NFT marketplace to make NSVs transferable.  And trying to convince Opensea or Blur or LooksRare to integrate something in order to make an NFT work on their marketplace will be like prying a can of tuna fish out of a tiger's mouth.

I am 100% certain that an escrow contract enforced transfer will make NSVs tradable on Opensea, Blur and other marketplaces out of the box.  We need a solution which supplies the necessary data for enforcement of NSV Safe state at the point of checkout in order to be compatible with current marketplaces.  That means an ECDSA + EIP1271 implementation built-in to an escrow contract which can enforce the validity of a user-owner' signature as well as the NSV state both at the point of offer and the point of sale.

**Comment by 0xdavinchee** [comment]
gm! After digesting the conversations and syncing w/ @daopunk, here is the implementation plan on how I would go about plugging this front running issue:

## Core issue

When a user buys ` a NFV, they can be frontrun and the value of the NFV can be altered prior to the transfer.

## Proposed solution

A hybrid solution which utilizes a time delay, where transfers can only happen after `n` time and a state hash+block.number comparison where the statehash must be equal and the block.number must be different than the current block of the transfer.

## Considered Contracts

### Vault721
```
struct HashState {
    uint256 lastHash;
    uint256 lastBlockNumber;
    uint256 lastBlockTime;
}
```
- [ ] Mapping from `vaultId` to `HashState` struct
  - [ ] setter function permissioned to onlyODSafeManager
- [ ] Mapping from `nftAddress` to `bool` whitelists (use state hash check)
  - [ ] setter function permissioned to onlyODSafeManager
- [ ] `timeDelay` property
  - [ ] setter function permissioned to onlyDAO
- [ ] `blockDelay` property
  - [ ] setter function permissioned to onlyDAO
- [ ] Checks in `_afterTokenTransfer`
  - [ ] A time-delay check: `require(block.timestamp - hashStateData[vaultId].lastBlockTime > timeDelay);`
  - [ ] A hash state check: `require(block.number > hashStateData[vaultId].lastBlockNumber);`

### SafeEngine
- [ ] Double check that any permissions granted from the ODSafeManager, e.g. `allowSAFE`, `allowHandler` does not open up the NFV collateral/debt amounts being modified via the SafeEngine directly (circumventing the ODSafeManager)

### ODSafeManager
- [ ] Question: Do we care about the internal coin balance being modified as well in the front running?
- [ ] Add a call to `vault721.updateVaultHashState(vaultId)` to all debt/collateral modifying functions:
  - [ ] `modifySAFECollateralization`
  - [ ] `transferCollateral(uint256 _safe, address _dst, uint256 _wad)`
  - [ ] `transferCollateral(bytes32 _cType, uint256 _safe, address _dst, uint256 _wad)`
  - [ ] `enterSystem(address _src, uint256 _safe)`
  - [ ] `quitSystem(uint256 _safe, address _dst)`
  - [ ] `moveSAFE(uint256 _safeSrc, uint256 _safeDst)`

### NFTRenderer
- [ ] A public function for getting the collateral and debt amounts for a vault, which can be reused by the existing `renderParams` function
- [ ] Include the `hash` as an attribute to the JSON text rendered for the tokenURI in the `renderParams` function and add as a property to `VaultParams` struct

## Misc
- [ ] Create another issue for the tests
- [ ] Create another issue for the governance scripts + governance scripts unit tests
