### ISSUE TITLE
Create Surplus + Debt in Anvil

### ISSUE THREAD

**Issue by daopunk** [open-dollar/od-contracts#287]
The frontend/backend team needs a script to efficiently create surplus and debt when running the local Anvil blockchain.

Goal:
- 3 scripts
- each script creates conditions for a specific type of auction
- instructions for running script for FE team

The FE team should be able to start an instance of Anvil, run these scripts independently to bring the state of the protocol to an auction, so the FE team can tests auctions on the app (UI) efficiently and locally

**Comment by St4rgarden** [comment]
Can you add a significant amount of additional context here please?

What are the instructions to run the local Anvil chain with the existing codebase?  Is the existing Anvil initialization process working or does it need to be fixed?  How exactly would the frontend/backend team like to call a script for creating surplus / debt?  Should it be essentially a `setUp()` type function that automatically initializes some surplus and debt during Anvil run initialization?  Do they need to be able to dynamically create surplus and debt for different accounts?

**Comment by daopunk** [comment]
After PR 282 is merged, Anvil is easier to run bc @0xdavinchee improved the yarn commands, so all you will have to run is `yarn deploy:anvil` which will move the deployments and run the node script, so you will have a fresh batch of protocol contracts for your local anvil instance. 

so yeah, run:
anvil
yarn deploy:anvil

**Comment by daopunk** [comment]
for record about this issue, from @pi0neerpat

```
yes. I should be able to, for instance, load the app locally, pointing to this chain, and see all 3 types of auctions
completed surplus auction
Ability to create a new surplus auction

completed debt auction
ability to start a new debt auction

completed collateral auctions
open collateral auctions
Since the protocol cannot be in both states to start a debt and surplus auction- there may need to be separate scripts for each type 
```
