### ISSUE TITLE
Single Test: Accounting Engine

### ISSUE THREAD

**Issue by daopunk** [open-dollar/od-contracts#303]
Resolve the failing tests for the Accounting Engine. Changes were made recently, which are likely causing these tests to fail

![Screenshot 2023-12-19 at 1 26 59 PM](https://github.com/open-dollar/od-contracts/assets/50965054/308cb4d3-d55b-4263-a5cb-28e721ad707e)

**Comment by pi0neerpat** [comment]
Reassigning to @MrDeadCe11

**Comment by MrDeadCe11** [comment]
That's cool. I already have it merged into a working branch.  It looks like
I will probably only need to add one or two tests to to cover the
accounting engine to 100%

**Comment by pi0neerpat** [comment]
Closed by #431
