### ISSUE TITLE
Test Coverage: Compare w/ HAI

### ISSUE THREAD

**Issue by daopunk** [open-dollar/od-contracts#307]
Open Dollar forked HAI before all tests were written. HAI has since expanded it's test coverage.

- Create unit tests for all contracts that do not have tests. You can compare with HAI repo to expedite process and help with writing tests.

**Comment by St4rgarden** [comment]
Yes I think identifying categories of tests will keep things nice discrete bite sized and manageable.

I will start investigating this when I come back to work on Tuesday and framing discrete chunks of test fixes.

**Comment by pi0neerpat** [comment]
Broken into separate issues
