### ISSUE TITLE
NFV Frontrunning Audit

### ISSUE THREAD

**Issue by daopunk** [open-dollar/od-contracts#319]
Reference to issue #277 that is being implemented by @0xdavinchee 

Task:
- Determine how collateral and debt amounts for a safe, identified by a SafeHandler assigned by the SafeManager, can be altered via direct calls to the SafeEngine
- Demonstrate attack vectors in praxis
- Assess whether these attack vectors can be mitigated with access control to the SafeEngine to prevent hostile actors from making direct calls to it, without obstructing the normal functioning of the protocol

Expected outcome:
- Audit report on the viability of the NFV frontrunning solution proposed in issue #277 
- Recommendation for improving proposal or disqualifying it as a viable solution

**Comment by St4rgarden** [comment]
Okay great I can get started on this next week as well.  <3

**Comment by pi0neerpat** [comment]
Hunter to follow up from conversation with Stargarden

**Comment by daopunk** [comment]
@St4rgarden the NFV Frontrunning changes have been implemented and merged by Vincent, but as you expressed initial concerns about the proposed solution, can you do an audit on this fix.

- write-up on vulnerabilities
- script executing vulnerability
- proposed fix

**Comment by pi0neerpat** [comment]
Depends on potential changes to NFV frontrunning solution eg adding ERC-

**Comment by pi0neerpat** [comment]
Addressed in current audit
