### ISSUE TITLE
Epic - uniswap v4 integration

### ISSUE THREAD

**Issue by cupOJoseph** [open-dollar/od-contracts#33]
Target mid fall 2023. Dependent on uniswap v4 release

- replace chainlink with hooks oracle
- governance around swapping pool incentives
- design pool incentives based on capital efficiency

**Comment by wei3erHase** [comment]
- integrate Uniswap to proxy actions to make a leveraged Safe position 👀

**Comment by cupOJoseph** [comment]
> * integrate Uniswap to proxy actions to make a leveraged Safe position 👀

hell yes. and also auto send LP token in the vault to make levered positions with those

**Comment by pi0neerpat** [comment]
Descoped
