### ISSUE TITLE
Create Instructions for Data Migration

### ISSUE THREAD

**Issue by daopunk** [open-dollar/od-contracts#330]
Create instructions for creating a data migration contract and list all data the needs to be transfered and how.

This could include a mock migration contract, but is not necessary. You decide.

If the migration process includes functionality of PR #271, then make note to @pi0neerpat and ask for approval for that PR and merge. Otherwise, close the PR with a reference to this data migration plan.

**Comment by pi0neerpat** [comment]
Closing, since a duplicate of https://github.com/open-dollar/od-contracts/issues/323
