### ISSUE TITLE
Prep for audit

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#335]
- Check issues missing from board
- identify issues remaining with "audit" label 

Later
- Create audit release
- Publish new forge contracts docs

**Comment by pi0neerpat** [comment]
On Feb 12, create a new contracts release to go to audit

**Comment by daopunk** [comment]
https://github.com/open-dollar/od-contracts/releases/tag/v1.6.2

https://github.com/open-dollar/od-relayer/releases/tag/v1.6.2

**Comment by pi0neerpat** [comment]
Done
