### ISSUE TITLE
Test coverage report

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#337]
Depends on #307 

- Run test coverage report using Slither
- Update readme with instructions for generating the report
- Research and make a recommendation for how to incorporate coverage to our devops CI/CD pipeline (eg Github actions)

**Comment by MrDeadCe11** [comment]
pr [here](https://github.com/open-dollar/od-contracts/pull/348)

**Comment by MrDeadCe11** [comment]
Pr merged.  closing issue.
