### ISSUE TITLE
Determine pool deployment history requirements

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#342]
in #170 we identified that the time / quote period comes from the CamelotPool, rather than inside the relayer.

```
    // This call may revert with 'OLD!' if the pool doesn't have enough cardinality or initialized history
```

In the pool code there is the warning above. We need to determine how much time must pass for a pool to have enough cardinality or initialized history, as this may impact deployment ops

**Comment by daopunk** [comment]
must pass `testCamelotRelayerPrice()` in od-relayer

**Comment by daopunk** [comment]
OLD is triggered if pool is read before interval time is reached
