### ISSUE TITLE
Coverage - Oracle

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#351]
Based on assessment in #338. Increase coverage for oracle contracts.

**Comment by pi0neerpat** [comment]
@daopunk would like your input here on whether we should be working on coverage here, or in https://github.com/open-dollar/od-relayer. Can you provide some clarity here so we do not accidentally duplicate work?

**Comment by daopunk** [comment]
@pi0neerpat i will make a separate isssue for od-relayers
