### ISSUE TITLE
Coverage - gov

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#354]
Based on assessment in https://github.com/open-dollar/od-contracts/issues/338. Increase coverage for gov contracts.

**Comment by pi0neerpat** [comment]
Assigning to @ngmachado as this may be a good place to get your feet wet.

**Comment by ngmachado** [comment]
@pi0neerpat we can close this issue.

**Comment by pi0neerpat** [comment]
Closed by #371
