### ISSUE TITLE
Vault721 sepolia verification

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#367]
Use the deploy singleton script to achieve contract verification for Vault721

https://sepolia.arbiscan.io/address/0x445f4bc91D3d96C968044328bF8cE59A7C2D56Da

**Comment by daopunk** [comment]
this is not working.

**Comment by pi0neerpat** [comment]
Tried with no success:
- Using forge CLI with the local bytecode
- Deployed just the singleton contract
- Deployed manually on Arbiscan
