### ISSUE TITLE
Add back disappeared audit label

### ISSUE THREAD

**Issue by jahabeebs** [open-dollar/od-contracts#382]
Audit label disappeared, add to label repo and manually add back to appropriate contract repos

**Comment by jahabeebs** [comment]
@pi0neerpat I've added back the 01/24 label to the .github repo and labeled all the repos that had that tag:

see view:

https://github.com/orgs/open-dollar/projects/1/views/17

however I noticed there was also a general "audit" tag you've been using since a while ago. do you want me to add that label back and re-label all the issues that had that tag as well?

**Comment by pi0neerpat** [comment]
Thank you! No we can ignore the plain "audit" label for now.
