### ISSUE TITLE
explore and set params for update incentives 

### ISSUE THREAD

**Issue by cupOJoseph** [open-dollar/od-contracts#39]
Amount to give as reward for completing jobs https://github.com/open-dollar/od-contracts/blob/6f52f46d2e85a1ccd0f97b82c5ffdf8afed00787/src/contracts/jobs/Job.sol

Decide on rewards for each contract:

- [ ] AccountingJob
- [ ] LiquidationJob
- [ ] OracleJob

**Comment by pi0neerpat** [comment]
Discussed, outcome in params hackmd
