### ISSUE TITLE
Research: Using dynamic trait standard and existing infra to safely trade NFV

### ISSUE THREAD

**Issue by cupOJoseph** [open-dollar/od-contracts#407]
# Requirement
determine if OpenSea can be used to safely trade NFVs

## Overview
NFV cant be traded normally without permissions because someone could mint debt after swap order is signed before it is executed in MEV attack.

## references
1. implementation of seaport zone that passes extraData field and uses that to verify meta data has not changed https://gist.github.com/ryanio/eaebeb59d8d29415ae9712f39ba4aac6
2. Seaport Improvement proposal which outlines their plan for handling ERC-7496 https://github.com/ProjectOpenSea/SIPs/blob/main/SIPS/sip-15.md
3. ERC 7496 dynamic trait NFTs: https://eips.ethereum.org/EIPS/eip-7496

**Comment by pi0neerpat** [comment]
Copied from #403 

Check that we adhere to the ERC-7496 standard https://eips.ethereum.org/EIPS/eip-7496

### ERC-7496 Standard

- Validate that swaps on OpenSea are using 7496
- When OpenSea trades 7496 tokens, would our implementation work as expected.

### OpenSea

- Check if OpenSea is on the allow-list, whether a swap will be successful

### Later

Ideally we can implement both our NFV Front running solution and ERC-7496

**Comment by pi0neerpat** [comment]
Complete
