### ISSUE TITLE
CamelotActions 1. Setup

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#412]
#411

Create `CamelotActions.sol`
- Inherit contract `CommonActions`
- New function`withdrawAllToVault(address _manager, address _collateralJoin,
    address _coinJoin, bytes32 _cType, address _camelotNft)`.  `collateralAmount` should be the full amount withdrawn from the pool. `deltaWad` hardcoded to 200 OD. 
- New function`withdrawToVault(address _manager, address _collateralJoin,
    address _coinJoin, bytes32 _cType, address _camelotNft, uint256 _collateralAmount, uint256 _deltaWad)`. This will allow us to prescribe how much collateral is deposited into the vault, and how much debt to generate. Whatever collateral is not deposited to the vault should be sent to back to the user. This also allows us to open an empty vault, in case the user's collateral is not great enough to mint the vault debt floor (eg their collateral is not enough to mint 200 OD)
- ODG rewards exited from the pool and sent to the user's wallet
- Follow pattern in BasicActions for `openLockTokenCollateralAndGenerateDebt`

**Comment by ngmachado** [comment]
no longer continuing TVL project by direction of team
