### ISSUE TITLE
CamelotActions 5. Fetch addresses

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#418]
Project #411

### Fetch addresses 

- Given a CamelotPool, read the addresses for all depositors
- Output a .csv file with all addresses
- Create another script which takes the above list and adds additional context to the csv:
     - total deposit amount
     - rewards
     - whether user has a proxy or not

**Comment by ngmachado** [comment]
no longer continuing TVL project by direction of team
