### ISSUE TITLE
Verify hai audit taxcollector

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#421]
Related to issue in #406

**Comment by daopunk** [comment]
Does Hai have a solution to the fake taxCollector issue from Code4rena audit?

It was not noted as an issue in the Hai Solidified audit...

**Comment by pi0neerpat** [comment]
Maybe there's no action on our part, and this issue is more of just verifying that they have implemented something to address this vulnerability (if there is one)

**Comment by daopunk** [comment]
The risk is low and the amount of tax avoided is low. 

![Image](https://github.com/open-dollar/od-contracts/assets/50965054/ec741e94-d651-42fe-89a7-da0cd2b243b6)
