### ISSUE TITLE
Update Gov Deployment Params

### ISSUE THREAD

**Issue by cupOJoseph** [open-dollar/od-contracts#429]
initialVotingDelay: 1 day - keep this short but give people time to buy more tokens before voting starts or un-LP and delegate

initialVotingPeriod: 6 days - no sneaking in proposals over the weekend

initialProposalThreshold: 10,000 votes - high enough to filter spam but low enough top delegates can make it

GovernorVotesQuorumFraction: 3%

https://github.com/open-dollar/od-contracts/blob/c7371d525422c18b0ce96d4778fc2aa5c9fc9feb/script/Registry.s.sol#L77

- [ ] change governance mode to use time instead of blocks

**Comment by pi0neerpat** [comment]
Outdated, replaced by #525
