### ISSUE TITLE
Review dependabot alerts

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#438]
See https://github.com/open-dollar/od-contracts/security/dependabot

**Comment by ngmachado** [comment]
After checking the alerts, i think we need to update our deps.

Please take into consideration that there will be a lot of breaking changes from OZ

e.g from hai https://github.com/hai-on-op/core/commit/81a07e62e0c875d07f4e291f40bd056da16abdd6

Some changes from OZ

>`GovernorStorage`: Added a new governor extension that stores the proposal details in storage, with an interface that operates on `proposalId`, as well as proposal enumerability. This replaces the old `GovernorCompatibilityBravo` module. ([#4360](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4360))


>`TimelockController`: During deployment, the TimelockController used to grant the `TIMELOCK_ADMIN_ROLE` to the deployer and to the timelock itself. The deployer was then expected to renounce this role once configuration of the timelock is over. Failing to renounce that role allows the deployer to change the timelock permissions (but not to bypass the delay for any time-locked actions). The role is no longer given to the deployer by default. A new parameter `admin` can be set to a non-zero address to grant the admin role during construction (to the deployer or any other address). Just like previously, this admin role should be renounced after configuration. If this param is given `address(0)`, the role is not allocated and doesn't need to be revoked. In any case, the timelock itself continues to have this role.`

**Comment by ngmachado** [comment]
## Security Alerts Review

### 1. `GovernorCompatibilityBravo` Calldata Verification

- **Issue**: There's a potential for `GovernorCompatibilityBravo` to mishandle proposal calldata if the number of signatures does not match the number of calldatas. 
- **Check Required**:
    
    `if (signatures.length != calldatas.length) {     throw new Error("GovernorBravo: invalid signatures length"); }`
    
- **Action Taken**: Noted for manual verification; however, it is not deemed critical to our current project setup.

### 2. Other Security Alerts

#### a. Improper Escaping of Output

- **Description**: Vulnerability related to improper escaping of output in OpenZeppelin contracts.
- **Relevance**: Not applicable to our codebase.

#### b. MerkleProof Multiproofs Vulnerability

- **Description**: Use of `MerkleProof` multiproofs in OpenZeppelin contracts might allow proving arbitrary leaves for specific trees.
- **Reference**: [npm package @openzeppelin/merkle-tree](https://www.npmjs.com/package/@openzeppelin/merkle-tree)
- **Relevance**: We build our own trees, and we should use merkle-tree lib to generate the tree itself. Don't see problem with this issue.

#### c. Governor Proposal Creation Frontrunning

- **Description**: Potential for governor proposal creation to be blocked by frontrunning in OpenZeppelin contracts.
- **Relevance**: Considered not relevant; should it become pertinent, the code will be updated to include frontrun protection.

#### d. TransparentUpgradeableProxy Clashing Selector Calls

- **Description**: Issues with clashing selector calls in `TransparentUpgradeableProxy` not being delegated properly.
- **Relevance**: Not relevant to our project.

#### e. Incorrect Calculation in Contracts

- **Description**: General alert regarding incorrect calculations in OpenZeppelin contracts.
- **Relevance**: Reviewed and found to be not relevant to our operations.

#### f. Base64 Encoding Memory Concerns

- **Description**: Alert regarding `base64` encoding processes in OpenZeppelin contracts that may access potentially dirty memory.
- **Relevance**: After review, not relevant to our project.
