### ISSUE TITLE
Modify safe fails unless OD is minted

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#443]
Related to https://github.com/open-dollar/od-app/issues/255

When modifying collateral in an existing safe, there is a requirement when repaying to also withdraw at least some OD. Determine if this is intended feature (eg. to prevent dust vaults) or for another reason. 

If its a bug, lets remove it.

**Comment by ngmachado** [comment]
@pi0neerpat is this issue still relevant after the PRs?

**Comment by pi0neerpat** [comment]
We won't know until the next deployment. Same thing for https://github.com/open-dollar/od-contracts/issues/417

**Comment by pi0neerpat** [comment]
@MrDeadCe11 can you verify that repaying works as expected? Eg. I should be able to modify my safe without having to generate debt.

**Comment by MrDeadCe11** [comment]
@pi0neerpat what errors are people getting when trying to repay debt?

**Comment by pi0neerpat** [comment]
Pretty certain its an issue with arbitrum sepolia network itself, so closing this issue
