### ISSUE TITLE
Anvil deployment missing StabilityFeeTreasury_Address

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#504]
When running test scripts against anvil deployment, there is no address in AnvilContracts.t.sol for StabilityFeeTreasury and SettlementSurplusAuctioneer

```js
Error: 
Compiler run failed:
Error (7576): Undeclared identifier.
  --> test/testlocal/nft/anvil/deployment/AnvilDeployment.t.sol:47:49:
   |
47 |     stabilityFeeTreasury = StabilityFeeTreasury(StabilityFeeTreasury_Address);
   |                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error (7576): Undeclared identifier.
  --> test/testlocal/nft/anvil/deployment/AnvilDeployment.t.sol:54:63:
   |
54 |     settlementSurplusAuctioneer = SettlementSurplusAuctioneer(SettlementSurplusAuctioneer_Address);
   |            
```

**Comment by ngmachado** [comment]
The address looks the right one, please check:

- that your deployer account is anvil first account (0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80)
- before the tests we should run `yarn deploy:anvil ` 

Debugging this issue i found out that the tests are broken anyway. Can we close this issue and create a specific one to fix the broken tests?

<img width="1643" alt="Screenshot 2024-03-15 at 14 34 47" src="https://github.com/open-dollar/od-contracts/assets/7188264/7d7c2b1f-49bd-4b2e-b3ff-d77df38518b0">

**Comment by pi0neerpat** [comment]
Still failing for me on `dev` branch. Specifically I'm trying to call the Anvil testing scripts (see readme) eg:

```
forge script script/states/DebtState.s.sol:DebtState --fork-url http://localhost:8545 -vvvvv
```
