### ISSUE TITLE
LiquidationEngine params getter reverts

### ISSUE THREAD

**Issue by daopunk** [open-dollar/od-contracts#510]
When calling LiquidationEngine.params(), the call reverts unexpectedly.

**Comment by MrDeadCe11** [comment]
it looks like the deployed liquidation engine params are
 ```  struct LiquidationEngineParams {
    // Max amount of system coins to be auctioned at the same time
    uint256 /* RAD */ onAuctionSystemCoinLimit;
  }```
  however the params that are in the repo are 
  ```
    struct LiquidationEngineParams {
    // Max amount of system coins to be auctioned at the same time
    uint256 /* RAD */ onAuctionSystemCoinLimit;
    // The gas limit for the saviour call
    uint256 /*       */ saviourGasLimit;
  }
```
so it looks like the sepolia liquidation engine needs to be updated to a newer contract.

**Comment by MrDeadCe11** [comment]
I tested the params getter on the audit deployment addresses and everything is working fine on the updated contracts.
