### ISSUE TITLE
Governance modify params script

### ISSUE THREAD

**Issue by daopunk** [open-dollar/od-contracts#511]
Depends on #594 

- Create a new script in `script/testScripts/gov/` which is flexible enough to update parameters for most protocol contracts (100% coverage is ideal, but not necessary)
- Create a template input file, similar to the one created in #594 to demonstrate its usage

**Comment by pi0neerpat** [comment]
Example https://github.com/open-dollar/od-contracts/pull/313/files

**Comment by pi0neerpat** [comment]
Closed by #598
