### ISSUE TITLE
Fix test in PIDRateSetter

### ISSUE THREAD

**Issue by daopunk** [open-dollar/od-contracts#516]
No code error. Is this test relevant? 

![Screenshot 2024-03-14 at 2 52 43 PM](https://github.com/open-dollar/od-contracts/assets/50965054/db69861e-9402-4c77-9af1-00655be3a603)

**Comment by ngmachado** [comment]
Yes, we now are checking coverage. We need to try to test all code path even if looks unnecessary. 

I will fix this test.
