### ISSUE TITLE
Review SepoliaParams.s.sol

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#524]
A few specific items are listed below, but a full review together with @daopunk is recommended

For now, lets only consider SepoliaParams; we will do mainnet params in following issue.

- [x] During sync about #522 we discussed confusion around debt ceiling. Specifically, the resulting ceilings in the sepolia testnet application do not match the expected values. For instance, the debt utilization percentages suggest varying debt ceilings

![image](https://github.com/open-dollar/od-contracts/assets/35622595/5ffdaca8-2898-488e-bfc3-1cd11d7b90ea)

- [x] SAFEEngineParams is using two different units (WAD and RAD)
```js
_safeEngineParams = ISAFEEngine.SAFEEngineParams({
      safeDebtCeiling: 10_000_000 * WAD, // WAD
      globalDebtCeiling: 25_000_000 * RAD // RAD
    });
```

**Comment by ngmachado** [comment]
The units WAD / RAD are correct

```javascript

struct SAFEEngineParams {
    // Total amount of debt that a single safe can generate
    uint256 /* WAD */ safeDebtCeiling;
    // Maximum amount of debt that can be issued across all safes
    uint256 /* RAD */ globalDebtCeiling;
  }

_safeEngineParams = ISAFEEngine.SAFEEngineParams({
      safeDebtCeiling: 10_000_000 * WAD, // WAD
      globalDebtCeiling: 25_000_000 * RAD // RAD
    });
```
