### ISSUE TITLE
OD-1 NFV Sale

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#528]
Audit

Depends on #542 

Pair with #534 

First step is starting a draft for implementing ERC-7496

**Comment by pi0neerpat** [comment]
During discussion in #542, we discovered the frontrunning checks are not being run for `safeTransferFrom`. This would allow a marketplace which implements `safeTransferFrom`, instead of `transferFrom` to avoid performing these checks.

**Comment by cupOJoseph** [comment]
references for handling dynamic meta data changes.
https://gist.github.com/ryanio/eaebeb59d8d29415ae9712f39ba4aac6

https://eips.ethereum.org/EIPS/eip-7496

**Comment by pi0neerpat** [comment]
Complete
