### ISSUE TITLE
OD-7 NFTRenderer representing full properties

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#534]
1. update NFTRenderer.VaultParams ✅ 
2. update NFTRenderer calls to pull new data ✅ 
3. update vault hash at `ODSafeManager.transferInternalCoins()` ✅ 
4. update: `coinBalance` and `tokenCollateral` cannot be added to the statehash. add direct check in transfer.

**Comment by pi0neerpat** [comment]
Surfacing a comment I made in January RE: statehash feature https://github.com/open-dollar/od-contracts/issues/328#event-11587322879

> The NFTRenderer was intentionally isolated, in order to reduce the security implications of making upgrades. I believe we should continue to keep it limited to only SVG image functionality. The hashState variable should be moved out of the renderer contract- likely to be in the 721 contract, since we need that data to persist.

**Comment by cupOJoseph** [comment]
The hashState variable should be moved out of the renderer contract- likely to be in the 721 contract, since we need that data to persist.

I agree with this 100%.

**Comment by cupOJoseph** [comment]
Note we agreed to on sync today:
moving on to OD 1 - since coinBalance and tokenCollateral are now part of the nft json, they can be used with dynamic trait eip safely
