### ISSUE TITLE
Check that all E2E Tests are Complete and Running

### ISSUE THREAD

**Issue by daopunk** [open-dollar/od-contracts#557]
The E2E Tests are all abstract, but at the bottom of the file inherit multiple contracts and run as non-abstract. The last merge with HAI may not have considered incomplete E2E test contracts.

Objective:
- check that are abstract contracts are being used
- check that all E2E tests are running in `yarn test`

**Comment by pi0neerpat** [comment]
Patrick to review https://github.com/open-dollar/od-contracts/pull/558 once this is completed
