### ISSUE TITLE
NFTRenderer cleanup

### ISSUE THREAD

**Issue by cupOJoseph** [open-dollar/od-contracts#563]
```solidity
  /**
   * @dev computes the current state hash based on the state for a vault given `_safeId`
   * @param _safeId vault id
   * @return stateHash state hash for safe with `_safeId`
   */
  function getStateHashBySafeId(uint256 _safeId) external view returns (bytes32 stateHash) {
    (, uint256 collateral, uint256 debt) = getVaultCTypeAndCollateralAndDebt(_safeId);
    stateHash = getStateHash(collateral, debt);
  }

  /**
   * @dev computes the current state hash given `_collateral` and `_debt`
   * @param _collateral collateral amount
   * @param _debt debt amount
   * @return stateHash computed state hash
   */
  function getStateHash(uint256 _collateral, uint256 _debt) public pure returns (bytes32 stateHash) {
    stateHash = keccak256(abi.encode(_collateral, _debt));
  }
```

- [ ] Update `getStateHash` to be `internal`. user should not be able to call random pure helper functions. helper functions should be private
- [ ] Move the stateHash struct to the same contract as the state hashing function
- [ ] (leftover from https://github.com/open-dollar/od-contracts/issues/328#issuecomment-1908575788) The NFTRenderer was intentionally isolated, in order to reduce the security implications of making upgrades. I believe we should continue to keep it limited to only SVG image functionality. The hashState variable should be moved out of the renderer contract- likely to be in the 721 contract, since we need that data to persist.
- [ ] Update the SVG url https://github.com/open-dollar/od-contracts/blob/dev/src/contracts/proxies/NFTRenderer.sol#L270C128-L270C195 based on the results from the discord pollhttps://discord.com/channels/874700997220515901/1192883248947265726/1225921971070697564

**Comment by pi0neerpat** [comment]
@cupOJoseph I was able to specify the tasks above. Can you provide more clarity on this one which I did not understand:

> - possibly different function for getting state hash vs computing and

**Comment by pi0neerpat** [comment]
Replaced by #600
