### ISSUE TITLE
Fix Dusty Liquidation

### ISSUE THREAD

**Issue by daopunk** [open-dollar/od-contracts#588]
In reference to #478 

Not merged during the final HAI merge bc it broke several unit tests for the LiquidationEngine contract.

**Comment by pi0neerpat** [comment]
Too important to wait for tech-debt

**Comment by daopunk** [comment]
single/SAFEEngine.t.sol: 2 fail / 17 succeed
`SingleLiquidationTest`
Reason: LiqEng_LiquidationLimitHit

unit/LiquidationEngine.t.sol: 8 fail / 24 succeed
`Unit_LiquidationEngine_LiquidateSafe`
Reason: vm.assume cheatcode rejected to many inputs

10 fail / 1789 succeed

**Comment by pi0neerpat** [comment]
Descoped
