### ISSUE TITLE
OD-6 cleanup

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#626]
- Remove `_dst` from arguments in quitSystem, and replace with the user's proxy
- Test that collateral can be exited from the protocol, all the way to the user's wallet, using `quitSystem`

Alternative solution is to disable `quitSystem` unless global shutdown is active

**Comment by daopunk** [comment]
`quit` or `quitSystem` migrates debt and collateral to a new safeHandler. It is not designed to exit to a user's wallet.

DAI

https://github.com/makerdao/dss-cdp-manager/blob/95eb088495239d6033e4ff4ccc28427adb20500b/src/DssCdpManager.sol#L229

RAI / GEB

https://github.com/reflexer-labs/geb-safe-manager/blob/e09403f6f59d53530e181da61db52c6b600da682/src/GebSafeManager.sol#L342
