### ISSUE TITLE
NFT testing cleanup

### ISSUE THREAD

**Issue by cupOJoseph** [open-dollar/od-contracts#65]
1. Check for NFT burning and safe access in
`src/test/nft/NFTSecurity.t.sol`
- User should not be able to burn NFT
- if things are burned make sure the correct owner only can access stuff

2. use arb goerli token addresses in setup in `src/test/nft/GoerliForkSetup.t.sol`. blocked by #3 

3. more tests for outside unknown proxies trying to interact in different ways

primarily show fuzzing and code coverage for all NFT changes

**Comment by pi0neerpat** [comment]
Fix failing tests. Return values are different now.

**Comment by pi0neerpat** [comment]
Update 9/19

### TODO

- Burning removed, still needs a test 
- Write more automated tests around the NFT
- Ensuring NFT additions have 100% code coverage
- Fuzzing
