### ISSUE TITLE
BasicActions _getGeneratedDeltaDebt precision issue

### ISSUE THREAD

**Issue by Seroxdesign** [open-dollar/od-contracts#665]
## Intended behaviour:

Tax is added onto borrowed amount, not reduced from what is sent to the user as per @cupOJoseph 

**Example:** 200 is borrowed, 200 OD is minted and sent to user, debt is incremented so they must pay back 200.01 

## Problem:

**Example:** When user's create a vault, and borrow 200 OD, only 199.98 is sent to their wallet, making it impossible for them to pay their debt without making a new vault, or obtaining OD.

We've investigate the Frontend, and SDK, the problem begins with the method:
[Contract & line](https://github.com/open-dollar/od-contracts/blob/66d7f86651261f86296d85cbf74082339cd8901a/src/contracts/proxies/actions/BasicActions.sol#L332C1-L344C4)

```TS
  function openLockTokenCollateralAndGenerateDebt(
    address _manager,
    address _collateralJoin,
    address _coinJoin,
    bytes32 _cType,
    uint256 _collateralAmount,
    uint256 _deltaWad
  ) external delegateCall returns (uint256 _safe) {
    _safe = _openSAFE(_manager, _cType, address(this));

    _lockTokenCollateralAndGenerateDebt(_manager, _collateralJoin, _coinJoin, _safe, _collateralAmount, _deltaWad);
  }
```

```_lockTokenCollateralAndGenerateDebt``` calls ```_getGeneratedDeltaDebt```

Which calculates _deltaDebt, however _deltaDebt is slightly off wad, potentially due to solidity precision loss issues. As seen below:
![image](https://github.com/open-dollar/od-contracts/assets/69639595/86475a99-f130-46a5-a1c7-e9e74209b36d)

```TS
// If there was already enough COIN in the safeEngine balance, just exits it without adding more debt
if (_coinAmount < _deltaWad * RAY) {
      // Calculates the needed deltaDebt so together with the existing coins in the safeEngine is enough to exit wad amount of COIN tokens
      _deltaDebt = ((_deltaWad * RAY - _coinAmount) / _rate).toInt();
      // This is neeeded due lack of precision. It might need to sum an extra deltaDebt wei (for the given COIN wad amount)
      _deltaDebt = uint256(_deltaDebt) * _rate < _deltaWad * RAY ? _deltaDebt + 1 : _deltaDebt;
 }
 ```

### Notes:

Maybe use hardhat console.log to print out every value within _getGeneratedDeltaDebt to see where the issue lies.

### Resources:

- [Tenderly Proof](https://dashboard.tenderly.co/tx/arbitrum/0x2f62ddae0ce1e761a384d2528311b6ffad4eedbc3f7de3eb84bc75cd42ad64b2?trace=0.0.0.2)
- [Arbiscan contract](https://arbiscan.io/address/0x6ebfce92cf88f4684cef44989c35910927a42e9c#code)

**Comment by MrDeadCe11** [comment]
this is how the protocol works.  You have to obtain OD on the open dollar to pay off your debt.  the protocol costs money to use.

**Comment by MrDeadCe11** [comment]
This is intended.  You have to obtain OD on the open market to pay off all your debt.  The protocol takes taxes any time the safe debt or collateral is modified.
