### ISSUE TITLE
GMX

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#721]
Research GMX

**Comment by MrDeadCe11** [comment]
# GMX

GMX is a decentralized spot and perpetual exchange.  They offer a rewards/Protocol token [$GMX](https://arbiscan.io/token/0xfc5A1A6EB076a2C7aD06eD22C90d7E710E35ad0a) that has a [$350m market cap](https://tokenterminal.com/terminal/projects/gmx) and an average 30 day trading volume of $5.96b with an average of 308.07k token holders across arbitrum and avalanche.  

there is a chainlink [GMX/USD](https://arbiscan.io/address/0xDB98056FecFff59D032aB628337A4887110df3dB) pricefeed on arbitrum.

**Comment by pi0neerpat** [comment]
Initial research is complete. 

gm may be too volatile and redemption mechanism may not be permisionless.
