### ISSUE TITLE
Pendle

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#722]
Research pendle

specifically for potential collateral types and oracles

**Comment by MrDeadCe11** [comment]
GYGP = Generic Yield Generating Pool
SY = standardized yield
PT = principal token (the principle token stripped of its yield)
YT = yield token (the yield of a token stripped of it's principle)
S = shares
t = time
u = user

![image](https://github.com/open-dollar/od-contracts/assets/84342118/890a28ed-078f-406c-b985-924981f7a167)



docs: https://github.com/pendle-finance/pendle-v2-resources/blob/main/whitepapers/SY.pdf

the base standardized yield contract:
https://github.com/pendle-finance/pendle-core-v2-public/blob/main/contracts/core/StandardizedYield/SYBase.sol

wsteth specific implementation:
https://github.com/pendle-finance/pendle-core-v2-public/blob/main/contracts/core/StandardizedYield/implementations/PendleWstEthSY.sol

PT tokens are always exchangeable 1 to 1 for their underlying asset.

YT oracle:
https://github.com/pendle-finance/pendle-core-v2-public/blob/main/contracts/oracles/PendlePYLpOracle.sol
