### ISSUE TITLE
Update test token naming

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#79]
Suggest completing with #132

#### Collateral

```
"WSTETH",
"CBETH",
"RETH",
"ARB",
"MAGIC",
```

- [x] Create a list of collateral we will launch with
- [x] ~Update the test tokens to match the same symbols / names as the launch collateral tokens~
- [x] These should still be deployed fresh each time (local and goerli)
- [x] Oracles should be OracleForTestnet

#### OD / ODG

- [x] Update the symbol/name for OD and ODG

**Comment by cupOJoseph** [comment]
wSteth
cbETH
rEth
Arb
Magic

**Comment by daopunk** [comment]
- replace Chainlink with oracleForTestnet
- deploy all tokens fresh each time for Anvil

**Comment by pi0neerpat** [comment]
I updated the correct token symbols above
